[terminal]
shell = { program = "/usr/bin/fish", args = ["-l"] }

[window]
padding = { x = 10, y = 10 }
opacity = 0.90
decorations = "Full"

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
size = 12.0

[scrolling]
history = 10000

[cursor]
style = { shape = "Beam", blinking = "Off" }

[selection]
save_to_clipboard = true

[colors.primary]
background = "#0d0d0d"
foreground = "#d8dee9"

[colors.cursor]
text = "#0d0d0d"
cursor = "#d8dee9"

[keyboard]
bindings = [
{ key = "PageUp", action = "ScrollPageUp" },
{ key = "PageDown", action = "ScrollPageDown" }
]

