[window]
padding = { x = 14, y = 12 }
decorations = "Full"
opacity = 0.90
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12.0

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 600
blink_timeout = 0

[selection]
save_to_clipboard = true

[colors.primary]
background = "#000000"
foreground = "#D7F9FF"

[colors.cursor]
text = "#000000"
cursor = "#00E5FF"

[colors.selection]
text = "#D7F9FF"
background = "#12343A"

[colors.normal]
black = "#000000"
red = "#FF5555"
green = "#50FA7B"
yellow = "#F1FA8C"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56D9E8"
white = "#D7F9FF"

[colors.bright]
black = "#555555"
red = "#FF6E6E"
green = "#69FF94"
yellow = "#FFFFA5"
blue = "#7AB7FF"
magenta = "#D78CFF"
cyan = "#00E5FF"
white = "#FFFFFF"
