# ============================================================
# RAIYAN // CLASSIC HACKER
# GREEN PHOSPHOR • OLD SCHOOL UNIX • MATRIX
# ============================================================

shell /usr/bin/zsh

font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 12

window_padding_width 16
window_padding_height 14

background_opacity 0.92
dynamic_background_opacity yes

hide_window_decorations yes
confirm_os_window_close 0

cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.55

scrollback_lines 10000

enable_audio_bell no
visual_bell_duration 0

linux_display_server wayland


# ───────── GREEN PHOSPHOR ─────────

background #020604
foreground #B8FFCB

cursor #39FF88
cursor_text_color #020604

selection_background #0B3D20
selection_foreground #D7FFE2


# ANSI

color0  #020604
color8  #193D29

color1  #E85D5D
color9  #FF7777

color2  #28E66F
color10 #5CFF98

color3  #9ACD32
color11 #B7E35A

color4  #238B45
color12 #35B85F

color5  #2DBE67
color13 #59E88A

color6  #38D996
color14 #65FFB0

color7  #9CC9A9
color15 #D9FFE3


# Links
url_color #52FF8C
underline_hyperlinks always

shell_integration enabled

repaint_delay 8
input_delay 0
sync_to_monitor yes

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

tab_bar_edge bottom
tab_bar_style powerline
tab_title_template "{index}: {title}"

map ctrl+shift+up increase_background_opacity
map ctrl+shift+down decrease_background_opacity
map ctrl+shift+0 set_background_opacity 1