# ============================================================
# RAIYAN // MODERN HACKER
# CYAN TERMINAL • CYBER SECURITY • FUTURISTIC
# ============================================================

shell /usr/bin/zsh

font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 12

window_padding_width 16
window_padding_height 14

background_opacity 0.92
dynamic_background_opacity yes

hide_window_decorations yes
confirm_os_window_close 0

cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.55

scrollback_lines 10000

enable_audio_bell no
visual_bell_duration 0

linux_display_server wayland


# ───────── CYAN ─────────

background #02070A
foreground #C7F9FF

cursor #22D3EE
cursor_text_color #02070A

selection_background #07343D
selection_foreground #D9FCFF


# ANSI

color0  #02070A
color8  #29444A

color1  #FF647C
color9  #FF879A

color2  #28D7A1
color10 #58F5C0

color3  #D7D86B
color11 #F0F28B

color4  #2AA7D6
color12 #5CCBFF

color5  #B879E8
color13 #D39AFF

color6  #22D3EE
color14 #67E8F9

color7  #A8CBD0
color15 #E4FCFF


# Links
url_color #67E8F9
underline_hyperlinks always

shell_integration enabled

repaint_delay 8
input_delay 0
sync_to_monitor yes

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

tab_bar_edge bottom
tab_bar_style powerline
tab_title_template "{index}: {title}"

map ctrl+shift+up increase_background_opacity
map ctrl+shift+down decrease_background_opacity
map ctrl+shift+0 set_background_opacity