# ============================================================
# RAIYAN // PROFESSIONAL HACKER
# MONOCHROME • UNIX • CLEAN • REALISTIC
# ============================================================

shell /usr/bin/zsh

font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 12

window_padding_width 16
window_padding_height 14

background_opacity 0.94
dynamic_background_opacity yes

hide_window_decorations yes
confirm_os_window_close 0

cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.55

scrollback_lines 10000

enable_audio_bell no
visual_bell_duration 0

linux_display_server wayland


# ───────── MONOCHROME ─────────

background #050505
foreground #D4D4D4

cursor #FFFFFF
cursor_text_color #050505

selection_background #303030
selection_foreground #FFFFFF


# ANSI

color0  #050505
color8  #555555

color1  #D06060
color9  #FF7777

color2  #8BC98B
color10 #B4E8B4

color3  #C8C078
color11 #E5DD9A

color4  #8FA8C8
color12 #B7CEEA

color5  #B49CC8
color13 #D1B9E8

color6  #8FBFBC
color14 #B8E4E0

color7  #BEBEBE
color15 #F5F5F5


# Links
url_color #FFFFFF
underline_hyperlinks always

shell_integration enabled

repaint_delay 8
input_delay 0
sync_to_monitor yes

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

tab_bar_edge bottom
tab_bar_style powerline
tab_title_template "{index}: {title}"

map ctrl+shift+up increase_background_opacity
map ctrl+shift+down decrease_background_opacity
map ctrl+shift+0 set_background_opacity 1