
general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
    no_fade_out = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.0
}

input-field {
    monitor =
    size = 300, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true

    outer_color = rgb(ffffff)
    inner_color = rgb(0b0b0b)
    font_color = rgb(ffffff)

    fade_on_empty = false
    placeholder_text = <i>Enter password...</i>

    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(ffffffee)
    font_size = 72
    font_family = JetBrains Mono NF

    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(aaaaaaee)
    font_size = 18
    font_family = JetBrains Mono NF

    position = 0, 20
    halign = center
    valign = center
}
